### ISSUE TITLE
Komunikat dla AdBlockersów

### ISSUE THREAD

**Issue by ImagoPL** [ImagoPL/surething-next#10]

**Comment by ImagoPL** [comment]
Fajnie, jakby działał dla wszystkich blokerów, bo teraz się to rozwarstwiło i mamy Adblocka, AdGuarda, uBlocka. Nie wiem, czy zrobić to prostą metodą, czy jednak postawić na wykrywanie po JS i wyświetlanie komunikatu.

**Comment by mat3osz** [comment]
Ogarniam temat i mam na razie block na 3 typy AdBlocków, rozbuduje to i dodam w środę

**Comment by ImagoPL** [comment]
@mat3osz - trzeba to przerobić, aby działało po stronie jQuery na wszystkich podstronach. Dasz radę? :)
