### ISSUE TITLE
Podpięcie Animsition

### ISSUE THREAD

**Issue by ImagoPL** [ImagoPL/surething-next#17]
http://git.blivesta.com/animsition/

Jak widać, pozwala stosować efektowne przejścia pomiędzy podstronami. Trzeba pamiętać przy wdrażaniu, aby animowane były tylko strony należące do ST. Wyjście poza ST powinno być IMO bez animacji.

@mat3osz - podepniesz? :)

**Comment by mat3osz** [comment]
Dzisiaj sobie obczaję jak to wygląda i na lokalnym się pobawię to Ci powiem na poniedziałek

**Comment by ImagoPL** [comment]
Póki co chodzi tylko o podpięcie samego skryptu. Będziemy z niego korzystać, jak już będzie co animować :smile:

**Comment by ImagoPL** [comment]
Zamknięte, pozostaje implementacja w kodzie.
