### ISSUE TITLE
Kategorie poboczne niewidoczne na głównej

### ISSUE THREAD

**Issue by TheChickenPie** [ImagoPL/surething-next#35]
Głównie chodzi mi o to, że działy takie, jak np. poradniki powinny być oddzielone od samej głównej, gdyż mogą być niezbyt interesujące dla czytelników. Ewentualnie oddziel ja jakąś przestrzenią na głównej, bo myślę, że ich celem będzie m.in. wyświetlanie ich w RSS.

**Comment by ImagoPL** [comment]
Jakie działy wg Ciebie nie powinny pokazywać się na głównej?

IMO powinniśmy raczej podzielić działy na te mniej i bardziej istotne i ułożyć je według tego kryterium zamiast rezygnować z wyświetlania częsci z nich. W końcu mogą one - jak każda inna treść - zachęcać do czytania. Dlatego IMO powinniśmy najważniejsze treści umieścić u góry głównej, a te najmniej ważne u dołu.

**Comment by TheChickenPie** [comment]
Opracuje to z Patrykiem i jutro Ci podeślemy z racji, iż dzisiaj wracamy do domu dopiero. :)

**Comment by ImagoPL** [comment]
Ok, czekam.

**Comment by ImagoPL** [comment]
@TheChickenPie - jak tam lista? Będzie na dzisiaj?

**Comment by TheChickenPie** [comment]
Będą to konkursy i poradniki. Z drugiej strony, to był głupi pomysł. Wydziel, jeżeli możesz, poradnikom, cyklom, konkursom i wpisom o grach oddzielne miejsce na głównej i tyle.

**Comment by ImagoPL** [comment]
No tak właśnie chciałem zrobić. Tylko trzeba to uporządkować, co u góry, co niżej. Według tego, co dla nas najistotniejsze.
