### ISSUE TITLE
Reader Mode

### ISSUE THREAD

**Issue by mat3osz** [ImagoPL/surething-next#57]
Tryb czytnika pozwalający skupić się na czytaniu. Przyciemnia on całą resztę witryny I wyodrębnia sam tekst - Coś jak "Reader Mode" w Safari 
https://vandadnp.files.wordpress.com/2011/02/safari-reader-mode.png 
(PS. Nie chciał mi się dodać obrazek - To dałem link)

**Comment by ImagoPL** [comment]
Solidne argumenty plz :)
