### ISSUE TITLE
Dodać prosty mechanizm podpowiadania podobnych wpisów do linkowania w trybie edycji

### ISSUE THREAD

**Issue by TheChickenPie** [ImagoPL/surething-next#68]

**Comment by ImagoPL** [comment]
Nie rozumiem. Rozwiń @TheChickenPie

**Comment by TheChickenPie** [comment]
Jak piszemy wpisy, często poruszamy tematykę innych, napisanych już artykułów. Czy dałoby się zrobić jakiś mechanizm, który podpowiadałby, że jest już wpis o podobnej tematyce, do którego można się odwołać?

**Comment by ImagoPL** [comment]
W panelu admina?

**Comment by TheChickenPie** [comment]
W rzeczy samej. W sumie, dobra, olejmy to, w sumie to beznadziejny pomysł. Usuń, proszę :)

**Comment by ImagoPL** [comment]
Też mi się tak wydaje, każdy raczej pamięta, jakie wpisy już u nas były i może je linkować w tekście. Zamykam.
