### ISSUE TITLE
Proste dzielenie akapitów we wpisie

### ISSUE THREAD

**Issue by TheChickenPie** [ImagoPL/surething-next#70]
Wraz z nowym motywem wejdzie mechanizm osi czasu. Będzie on pewnie we wpisach podzielony po nagłówkach (tak przynajmniej zgaduje, recki to recki) i warto byłoby zrobić jakiś mechanizm, który by je automatycznie na osi czasu oznaczał. :)

**Comment by ImagoPL** [comment]
@TheChickenPie #65 ?

**Comment by TheChickenPie** [comment]
Yup. Brak aplikacji na WP mnie wkurza, bo nie widzę wszystkich komentarzy :/
